export const FETCH_FOOD_TRUCKS = 'FETCH_FOOD_TRUCKS'
export const FETCH_FOOD_TRUCKS_SUCCESS = 'FETCH_FOOD_TRUCKS_SUCCESS'
export const FETCH_FOOD_TRUCKS_ERROR = 'FETCH_FOOD_TRUCKS_ERROR'
export const CHANGE_BOUNDING_BOX = 'CHANGE_BOUNDING_BOX'
